name: UberCraft
version: 1.6
main: com.foxsrv.ubercraft.UberCraft
api-version: 1.20
depend: [CoinCard]
author: FoxOficial2
description: Uber system for Minecraft using CoinCard payments

commands:
  uber:
    description: Main Uber command
    usage: /uber <x y z|warp|cancel|admin>
    aliases: [u]
  ubergui:
    description: Open Uber requests menu
    usage: /ubergui
    aliases: [ug]

permissions:
  uber.player:
    description: Can request Uber rides
    default: true
  uber.uber:
    description: Can accept Uber rides
    default: op
  uber.admin:
    description: Can manage warps
    default: op
    children:
      uber.uber: true
